### ISSUE TITLE
Arrow spinning around

### ISSUE THREAD

**Issue by ilreberli** [Hydra9268/ZGESO#11]
I installed ZGESO yesterday and I remarked, that the arrow is spinning around all the time in constant speed. I am completely new to ESO (installed 1 day ago) so please concern this with your advice and btw. I am using MacOS Mojave.

The only hint I can give you is:  After installing ESO I had a similar effect with the camera view (the room was spinning around all the time) after entering ESO with my character. There was a hint at ESO for that problem "if you have this issue just open System Preferences>Security and Privacy. Go on Privacy tab. Click on the lock on the left bottom corner, enter your password and check "ESO" and "Zenimax Online Studio Launcher". This solved the problem of the camera view, but the spinning arrow reminds me to this.

Hope you have a solution for this.

**Comment by Hydra9268** [comment]
This should be fixed in an update
