### ISSUE TITLE
Conflict with another addon

### ISSUE THREAD

**Issue by danilokhury** [Hydra9268/ZGESO#12]
Hey there, love the work with the addon. Just having one small issue with it. I use DarkUI addon and if Zygor is Enabled whenever i enable cursor mode i open the big map in the middle of the screen.

This only happens when Zygor is payer with DarkUI minimap enabled.

**Comment by Hydra9268** [comment]
Zygor authored the core code. It has received updates throughout its lifespan ever since Zygor released it as a public domain, but a complete revamp is impossible to make it play nice with every addon.
