### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Deriol** [Hydra9268/ZGESO#2]
I cant seem to get it to work since the most recent update?  I dropped the folder into my addons directory and renamed the folder to ZygorGuidesViewer  but it is not showing up in my addons.  There is no clear installation instructions on the page.  I had to revert to an older version from several weeks ago and renamed the folder ZygorGuidesViewer and it worked.  Sorry new to github not sure how to add flairs.  XD

**Comment by Hydra9268** [comment]
Hi, Deriol.

1. Keep the folder name as ZGESO. If you change to ZygorGuidesViewer, ZG's launcher will revert the code to an older, outdated state.
2. Go to the Add-ons menu inside ESO's main menu and uncheck Zygor's Guide. You want to use "Leveling Guides v1.4.0.217," which is the name of this guide.

Lastly, I recommend installing through Minion. The version I deployed on ESOUI.com is the most recent stable release of the guide. Plus, it's easier to use. The Github version is in continual development and may "break."

**Comment by Deriol** [comment]
Did not realize it was on minion now as well.  Followed the link from forums about a month ago to this github here.  I guess this is resolved now then XD
