### ISSUE TITLE
Navigation arrow not showing

### ISSUE THREAD

**Issue by robotpukeko** [Hydra9268/ZGESO#3]
Set the add-on to be the only one active, but only the quest window will show in the UI. The navigation arrow won't show, even if I reset to default settings.

The following was generated from the bug option : 

`bad argument #3 to 'string.format' (string expected, got nil)
stack traceback:
[C]: in function 'string.format'
user:/AddOns/ZGESO/BugReport.lua:210: in function 'BugReport:GetReport'
user:/AddOns/ZGESO/BugReport.lua:251: in function 'BugReport:ShowReport'
user:/AddOns/ZGESO/Viewer/GuideViewerFrame.lua:211: in function '(anonymous)'`

**Comment by robotpukeko** [comment]
Arrow was not showing for a wayshrine step. Navigating to the next solved the issue.

**Comment by Hydra9268** [comment]
Thanks for reporting this. Which guide and step? I'd still like to take a look.
