### ISSUE TITLE
Unable to load guide

### ISSUE THREAD

**Issue by ItzSteveHuh** [Hydra9268/ZGESO#4]
Here's the UI Errors I get using this verison
user:/AddOns/ZGESO/Functions.lua:231: Attempt to call a table value
stack traceback:
user:/AddOns/ZGESO/Functions.lua:231: in function 'table.zgclone'
user:/AddOns/ZGESO/Options.lua:964: in function 'SavedVars:CreateNewCharProfile'
user:/AddOns/ZGESO/Options.lua:1094: in function 'copySvOldToNew'
user:/AddOns/ZGESO/Options.lua:868: in function 'SavedVars:Setup'
user:/AddOns/ZGESO/ZGESO.lua:202: in function 'ZGV_Initialized'

user:/AddOns/ZGESO/ZGESO.lua:217: ZGV failed to initialize, and player is already activated. ABORTING!
stack traceback:
[C]: in function 'error'
user:/AddOns/ZGESO/ZGESO.lua:217: in function 'ZGV_NotInitialized'

**Comment by Hydra9268** [comment]
Fixed. Download the latest.

**Comment by Hydra9268** [comment]
Fixed. Download the latest.
