### ISSUE TITLE
Stonefalls Guide

### ISSUE THREAD

**Issue by Minky4981** [Hydra9268/ZGESO#48]
After leaving Sheogorath's Tounge, Step 628, all subsequent map co-ords now point to Sheogorath's Tongue and not Stonefalls, the issue resolves after step 660 where you go to Kraenmoor.
![ZGESO1](https://user-images.githubusercontent.com/88851542/129246170-9c6fca73-ed6c-4510-80aa-08c153e50688.JPG)
![2](https://user-images.githubusercontent.com/88851542/129246177-bdbe4d7d-26eb-480d-b957-f8e47480b196.JPG)
![4](https://user-images.githubusercontent.com/88851542/129246187-65777780-afd0-4eab-b1b8-2bd6ed12734f.JPG)

**Comment by Hydra9268** [comment]
Thank you @Minky4981.

**Comment by Hydra9268** [comment]
Hi, @Minky4981. I wasn't able to reproduce this issue. It might have been a hiccup as you transitioned between the delve and the map.
