### ISSUE TITLE
Elsweyr/Summerset update?

### ISSUE THREAD

**Issue by Jadax** [Hydra9268/ZGESO#6]
Just wondering if this will be updated for Elsweyr and Summerset.

**Comment by RangerCoder99** [comment]
Wondering the same... seems that Jadax maybe no longer working on it as the last release was 5 months ago.

**Comment by Hydra9268** [comment]
All good guys. Check out my reply on the esoui forums.
https://www.esoui.com/downloads/fileinfo.php?id=2062#comments
